version: '3'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./../../../Graphs:/fed-flow/Graphs
      - ./../../../app/logs:/fed-flow/app/logs
    image: autlpdslab/fedflow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - broker
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -sb True -s fake_splitting -e False & python3 /fed-flow/energy/service.py"

  broker:
    attach: false
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker